name: Trivy Action

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build ConsoleAppWithVulnerableLibrary image
        run: docker build -f Dockerfile.ConsoleAppWithVulnerableLibrary -t app1 .

      - name: Build VulnerableConsoleApp image
        run: docker build -f Dockerfile.VulnerableConsoleApp -t app2 .

      - name: Scan app1 with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'app1'

      - name: Scan app2 with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'app2'
