name: Trivy Action

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish ConsoleAppWithVulnerableLibrary
        run: dotnet publish ConsoleAppWithVulnerableLibrary/ConsoleAppWithVulnerableLibrary.csproj -c Release -o ./ConsoleAppWithVulnerableLibrary/publish

      - name: Build Docker image
        run: docker build -f Dockerfile.ConsoleAppWithVulnerableLibrary -t app1 .

      - name: Scan app1 image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'app1'

      - name: Scan NuGet dependencies with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './ConsoleAppWithVulnerableLibrary/publish'
